const letterConfig = {
  first:
    "1 Nel mezzo del cammin di nostra vita 2 mi ritrovai per una selva oscura, 3 che la diritta via era smarrita. 4 Ahi quanto a dir qual era è cosa dura 5 esta selva selvaggia e aspra e forte 6 che nel pensier rinova la paura! 7 Tantʼ è amara che poco è più morte; 8 ma per trattar del ben chʼiʼ vi trovai， 9 dirò de lʼaltre cose chʼiʼ vʼho scorte. 10 Io non so ben ridir comʼ iʼ vʼintrai, 11 tantʼ era pien di sonno a quel punto 12 che la verace via abbandonai. 13 Ma poi chʼiʼ fui al piè dʼun colle giunto, 14 là dove terminava quella valle 15 che mʼavea di paura il cor compunto, 16 guardai in alto e vidi le sue spalle 17 vestite già deʼ raggi del pianeta 18 che mena dritto altrui per ogne calle. 19 Allor fu la paura un poco queta, 20 che nel lago del cor mʼera durata 21 la notte chʼiʼ passai con tanta pieta. 22 E come quei che con lena affannata, 23 uscito fuor del pelago a la riva, 24 si volge a lʼacqua perigliosa e guata, 25 così lʼanimo mio, chʼancor fuggiva,",
  second:
    "26 si volse a retro a rimirar lo passo 27 che non lasciò già mai persona viva. 28 Poi chʼèi posato un poco il colpo lasso, 29 ripresi via per la piaggia diserta, 30 sì che ʼl piè fermo sempre era ʼl più basso. 31 Ed ecco, quasi al cominciar de lʼerta, 32 una lonza leggera e presta molto, 33 che di pel macolato era coverta; 34 e non mi si partia dinanzi al volto, 35 anzi ʼmpediva tanto il mio cammino, 36 chʼiʼ fui per ritornar più volte vòlto. 37 Tempʼ era dal principio del mattino, 38 e ʼl sol montava ʼn sù con quelle stelle 39 chʼeran con lui quando lʼamor divino 40 mosse di prima quelle cose belle; 41 sì chʼa bene sperar mʼera cagione 42 di quella fiera a la gaetta pelle 43 lʼora del tempo e la dolce stagione; 44 ma non sì che paura non mi desse 45 la vista che mʼapparve dʼun leone. 46 Questi parea che contra me venisse 47 con la testʼ alta e con rabbiosa fame, 48 sì che parea che lʼaere ne tremesse. 49 Ed una lupa, che di tutte brame 50 sembiava carca ne la sua magrezza, 51 e molte genti fé già viver grame, 52 Questa mi porse tanto di gravezza 53 con la paura chʼuscia di sua vista,",
  third:
    "54 chʼio perdei la speranza de lʼaltezza. 55 E qual è quei che volontieri acquista, 56 e giugne ʼl tempo che perder lo face, 57 che ʼn tutti suoi pensier piange e sʼattrista; 58 tal mi fece la bestia sanza pace, 59 che, venendomi ʼncontro, a poco a poco 60 mi ripigneva là dove ʼl sol tace. 61 Mentre chʼiʼ rovinava in basso loco, 62 dinanzi a li occhi mi si fu offerto 63 chi per lungo silenzio parea fioco. 64 Quando vidi costui nel gran diserto, 65 “Miserere di me”, gridai a lui, 66 “qual che tu sii, od ombra od omo certo!”. 67 Rispuosemi: “Non omo, omo già fui, 68 e li parenti miei furon lombardi, 69 mantoani per patrïa ambedui. 70 Nacqui sub Iulio, ancor che fosse tardi, 71 e vissi a Roma sotto ʼl buono Augusto 72 nel tempo de li dèi falsi e bugiardi. 73 Poeta fui, e cotai di quel giusto 74 figliuol dʼAnchise che venne di Troia, 75 poi che ʼl superbo Ilïón fu combusto. 76 Ma tu perché ritorni a tanta noia? 77 perché non sali il dilettoso monte 78 chʼè principio e cagion di tutta gioia?”. 79 “Or seʼ tu quel Virgilio e quella fonte 80 che spandi di parlar sì largo fiume?”, 81 rispuosʼ io lui con vergognosa fronte.",
  fourth:
    "82 “O de li altri poeti onore e lume, 83 vagliami ʼl lungo studio e ʼl grande amore 84 che mʼha fatto cercar lo tuo volume. 85 Tu seʼ lo mio maestro e ʼl mio autore, 86 tu seʼ solo colui da cuʼ io tolsi 87 lo bello stilo che mʼha fatto onore. 88 Vedi la bestia per cuʼ io mi volsi; 89 aiutami da lei, famoso saggio, 90 chʼella mi fa tremar le vene e i polsi”. 91 “A te convien tenere altro viaggio”, 92 rispuose, poi che lagrimar mi vide, 93 “se vuoʼ campar dʼesto loco selvaggio; 94 ché questa bestia, per la qual tu gride, 95 non lascia altrui passar per la sua via, 96 ma tanto lo ʼmpedisce che lʼuccide; 97 e ha natura sì malvagia e ria, 98 che mai non empie la bramosa voglia, 99 e dopo ʼl pasto ha più fame che pria. 100 Molti son li animali a cui sʼammoglia, 101 e più saranno ancora, infin che ʼl veltro 102 verrà, che la farà morir con doglia. 103 Questi non ciberà terra né peltro, 104 ma sapïenza, amore e virtute, 105 e sua nazion sarà tra feltro e feltro. 106 Di quella umile Italia fia salute 107 per cui morì la vergine Cammilla, 108 Eurialo e Turno e Niso di ferute. 109 Questi la caccerà per ogne villa,",
};

export { letterConfig };
